docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - touch .env
    - echo PORT=8080 >> .env
    - echo BRANCH_NAME="$CI_COMMIT_REF_NAME" >> .env
    - echo COMMIT_HASH="$CI_COMMIT_SHA" >> .env
    - echo PIPELINE_ID="$CI_PIPELINE_ID" >> .env
    - echo DEPLOYMENT_DATE=$(date) >> .env
    - echo DEPLOYED_COMMIT_AUTHOR="$CI_COMMIT_AUTHOR" >> .env

    - echo $GCP_SERVICE_KEY > ./lib/service_account.json
    - cat ./lib/service_account.json | docker login -u _json_key --password-stdin gcr.io

  script:
    - tag="gcr.io/${GCP_PROJECT_ID}/react-bike-rentals"
    - docker build --pull -t "${tag}" .
    - docker push "${tag}"

  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

deploy:
  stage: deploy
  image: google/cloud-sdk
  services:
    - docker:dind
  needs: ["docker-build"]
  script:
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yml
