import { BikesGrid } from "@components/organisms";
import { useBikes } from "hooks";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { bikes } = useBikes();
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <BikesGrid bikes={bikes} />
        </div>
      </main>
    </div>
  );
};

export default Home;
