import { GetServerSideProps } from "next";
import Head from "next/head";
import { FunctionComponent } from "react";
import styles from "../../styles/Home.module.css";
import { getAuthUser } from "helpers";

interface DashboardProps {}

const Dashboard: FunctionComponent<DashboardProps> = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
};

export default Dashboard;